import sys
import logging
import json
import pyspark.sql
import subprocess
from pyspark import SparkContext
from pyspark.context import SparkContext
from pyspark.sql.session import SparkSession
from pyspark.sql.types import *
from pyspark.sql.functions import *

#def carregaLib():
#    _getLibs = "/data/source/lib"
#    cmd = ['hdfs', 'dfs', '-get', _getLibs, '.']
#    subprocess.check_output(cmd).strip().split('\n')
#    sys.path.insert(0, "lib")
#carregaLib()
#
##import Constants.Variables as var
#import Constants.Mensage as msg
#import Constants.Path as p
##import Dados.DadosIO as db
##import Model.fin_proposta as model
#import Util.Function as ut_f
##import Config.Constants as conf

sc = SparkContext('local')
spark = SparkSession(sc)
session = SparkSession.builder.getOrCreate()

schema = StructType([
                     StructField("cabecalho",StructType([
                            StructField("cpf", StringType(), True),
                            StructField("telefone",StringType(), True),
                            StructField("timestamp", StringType(), True),
                            StructField("identificador-job", StringType(), True),
                            StructField("session-id", StringType(), True),
                            StructField("sistema-origem", StringType(), True),
                            StructField("tipo-transacao", StringType(), True)
                                    ])),
                     StructField("output-motor-analise-full",StructType([
                            StructField('similaridadeFoneticaCadSerasa', StringType(), True),
                            StructField('similaridadeFoneticaCadAllCheck', StringType(), True),
                            StructField('similaridadeFoneticaCadTelesign', StringType(), True),
                            StructField('ratingFraudeFull', StringType(), True),
                            StructField('ratingDti', StringType(), True),
                            StructField('ratingQuod', StringType(), True),
                            StructField('ratingSim', StringType(), True),
                            StructField('ratingFinanceira', StringType(), True),
                            StructField('ratingFinal', StringType(), True),
                            StructField('statusDecisaoFull', StringType(), True),
                            StructField('cmasDirecionamentos', StringType(), True),
                            StructField('apontamentoGrupo1', StringType(), True),
                            StructField('apontamentoGrupo2', StringType(), True),
                            StructField('apontamentoGrupo3', StringType(), True),
                            StructField('apontamentoGrupo4', StringType(), True),
                            StructField('apontamentoGrupo5', StringType(), True),
                            StructField('apontamentoGrupo6', StringType(), True),
                            StructField('apontamentoGrupo7', StringType(), True),
                            StructField('apontamentoGrupo8', StringType(), True),
                            StructField('apontamentoGrupo9', StringType(), True),
                            StructField('apontamentoGrupo10', StringType(), True),
                            StructField('reasoncodeBlaze1', StringType(), True),
                            StructField('reasoncodeBlaze2', StringType(), True),
                            StructField('reasoncodeBlaze3', StringType(), True),
                            StructField('reasoncodeBlaze4', StringType(), True),
                            StructField('reasoncodeBlaze5', StringType(), True),
                            StructField('reasoncodeBlaze6', StringType(), True),
                            StructField('reasoncodeBlaze7', StringType(), True),
                            StructField('reasoncodeBlaze8', StringType(), True),
                            StructField('reasoncodeBlaze9', StringType(), True),
                            StructField('reasoncodeBlaze10', StringType(), True),
                            StructField('mensagemReasoncode1', StringType(), True),
                            StructField('mensagemReasoncode2', StringType(), True),
                            StructField('mensagemReasoncode3', StringType(), True),
                            StructField('mensagemReasoncode4', StringType(), True),
                            StructField('mensagemReasoncode5', StringType(), True),
                            StructField('mensagemReasoncode6', StringType(), True),
                            StructField('mensagemReasoncode7', StringType(), True),
                            StructField('mensagemReasoncode8', StringType(), True),
                            StructField('mensagemReasoncode9', StringType(), True),
                            StructField('mensagemReasoncode10', StringType(), True)
                     ])),
                     StructField("logInput",StructType([
                            StructField('vivereIdProposta', StringType(), True),
                            StructField('vivereDataProposta', StringType(), True),
                            StructField('vivereCampanha', StringType(), True),
                            StructField('vivereDiaSemanaInclusao', StringType(), True),
                            StructField('vivereTimestampRequisicao', StringType(), True),
                            StructField('vivereCpfCliente', StringType(), True),
                            StructField('vivereDataNascimento', StringType(), True),
                            StructField('vivereDataUltimoResetSenha', StringType(), True),
                            StructField('vivereSessionId', StringType(), True),
                            StructField('vivereIP', StringType(), True),
                            StructField('vivereDescricaoDevice', StringType(), True),
                            StructField('vivereGeolocalizacaoDevice', StringType(), True),
                            StructField('financeiraCodigoProduto', StringType(), True),
                            StructField('financeiraTipoPessoa', StringType(), True),
                            StructField('dmpsQuantidadeDiasCarencia', StringType(), True),
                            StructField('financeiraCodigoObjeto', StringType(), True),
                            StructField('dmpsIdade', StringType(), True),
                            StructField('vivereVeiculoMarca', StringType(), True),
                            StructField('vivereVeiculoAnoModelo', StringType(), True),
                            StructField('vivereVeiculoAnoFabricacao', StringType(), True),
                            StructField('vivereVeiculoUfPlaca', StringType(), True),
                            StructField('vivereVeiculoUfLicenciamento', StringType(), True),
                            StructField('vivereVeiculoValorFIPE', StringType(), True),
                            StructField('vivereCedenteCnpj', StringType(), True),
                            StructField('vivereBoletoValorAPagar', StringType(), True),
                            StructField('vivereBoletoDataVencimento', StringType(), True),
                            StructField('vivereCedenteBanco', StringType(), True),
                            StructField('vivereFaturaValorAPagar', StringType(), True),
                            StructField('vivereFaturaDataVencimento', StringType(), True),
                            StructField('vivereBanco', StringType(), True),
                            StructField('vivereSubSegmento', StringType(), True),
                            StructField('vivereTAB', StringType(), True),
                            StructField('vivereValorSolicitado', StringType(), True),
                            StructField('vivereValorFinanciado', StringType(), True),
                            StructField('vivereParcela', StringType(), True),
                            StructField('viverePrazo', StringType(), True),
                            StructField('vivereTaxaNominalMensal', StringType(), True),
                            StructField('vivereTaxaNominalAnual', StringType(), True),
                            StructField('vivereTaxaCETMensal', StringType(), True),
                            StructField('vivereTaxaCETAnual', StringType(), True),
                            StructField('vivereFormaPagamento', StringType(), True),
                            StructField('vivereDataVencimentoSelecionada', StringType(), True),
                            StructField('vivereDataVencimentoPrimeiraParcela', StringType(), True),
                            StructField('vivereProponenteSexo', StringType(), True),
                            StructField('vivereProponenteNaturalidadeUF', StringType(), True),
                            StructField('vivereProponenteNaturalidadeCidade', StringType(), True),
                            StructField('vivereProponenteProfissao', StringType(), True),
                            StructField('vivereProponenteRenda', StringType(), True),
                            StructField('vivereProponenteCEP', StringType(), True),
                            StructField('vivereProponenteLogradouro', StringType(), True),
                            StructField('vivereProponenteEstado', StringType(), True),
                            StructField('vivereProponenteCidade', StringType(), True),
                            StructField('vivereAvalistaParentesco', StringType(), True),
                            StructField('vivereAvalistaCPF', StringType(), True),
                            StructField('vivereAvalistaDataNascimento', StringType(), True),
                            StructField('vivereAvalistaRenda', StringType(), True),
                            StructField('vivereAvalistaCEP', StringType(), True),
                            StructField('vivereAvalistaLogradouro', StringType(), True),
                            StructField('vivereAvalistaEstado', StringType(), True),
                            StructField('vivereAvalistaCidade', StringType(), True),
                            StructField('vivereOcupacao1', StringType(), True),
                            StructField('vivereRenda1', StringType(), True),
                            StructField('vivereOcupacao2', StringType(), True),
                            StructField('vivereRenda2', StringType(), True),
                            StructField('vivereOcupacao3', StringType(), True),
                            StructField('vivereRenda3', StringType(), True),
                            StructField('vivereOcupacao4', StringType(), True),
                            StructField('vivereRenda4', StringType(), True),
                            StructField('vivereOcupacao5', StringType(), True),
                            StructField('vivereRenda5', StringType(), True),
                            StructField('vivereNomeEmpresa', StringType(), True),
                            StructField('vivereDataAdmissao', StringType(), True),
                            StructField('vivereCNPJ', StringType(), True),
                            StructField('vivereFonteRendaCEP', StringType(), True),
                            StructField('vivereFonteRendaEstado', StringType(), True),
                            StructField('vivereFonteRendaCidade', StringType(), True),
                            StructField('financeiraRepesc', StringType(), True),
                            StructField('financeiraCdtQtdPefinRes6MCli', StringType(), True),
                            StructField('financeiraCdtQtdPefinRes12MCli', StringType(), True),
                            StructField('financeiraQtdOcoAtvSerasaCli', StringType(), True),
                            StructField('financeiraTmpOcoAtvNegMRecCli', StringType(), True),
                            StructField('financeiraTmpOcoResNegMRecCli', StringType(), True),
                            StructField('financeiraQtdOcoAcm1d12MCli', StringType(), True),
                            StructField('financeiraCdtQtdOcoAcm90d12MCli', StringType(), True),
                            StructField('financeiraVlrMaxOcoNeg12MCli', StringType(), True),
                            StructField('financeiraCdtTmpOcoNegRec12MCli', StringType(), True),
                            StructField('financeiraCdtVlrTotOcoNeg12MCli', StringType(), True),
                            StructField('financeiraCdtTmpMdRResSccf12MCli', StringType(), True),
                            StructField('financeiraCdtQtdCcfAtv12MCli', StringType(), True),
                            StructField('financeiraCdtQtdCcfRes12MCli', StringType(), True),
                            StructField('financeiraCdtQtdCcfAtvCli', StringType(), True),
                            StructField('financeiraCdtQtdAcoesRes12MCli', StringType(), True),
                            StructField('financeiraCdtQtdRefinAtvCli', StringType(), True),
                            StructField('financeiraCdtQtdRefinAtv12MCli', StringType(), True),
                            StructField('financeiraCdtQtdRefinRes6MCli', StringType(), True),
                            StructField('financeiraCdtQtdRefinRes12MCli', StringType(), True),
                            StructField('financeiraCdtQtdPefinAtvCli', StringType(), True),
                            StructField('financeiraQtdPefinAtv12MCli', StringType(), True),
                            StructField('financeiraQtdProAtvCli', StringType(), True),
                            StructField('financeiraQtdProRes12MCli', StringType(), True),
                            StructField('financeiraQtdRestAtvRes12MCli', StringType(), True),
                            StructField('financeiraQtdAcoesAtvCli', StringType(), True),
                            StructField('financeiraCdtIcConsultaCadusCli', StringType(), True),
                            StructField('financeiraCdtCdExperAbn', StringType(), True),
                            StructField('financeiraCdtCdExperAbnAv1', StringType(), True),
                            StructField('financeiraCdtQtUsoCpf', StringType(), True),
                            StructField('financeiraCdtCdCrb', StringType(), True),
                            StructField('financeiraCdtCdCrbAv1', StringType(), True),
                            StructField('financeiraCdtRatingClassif', StringType(), True),
                            StructField('financeiraCdtRatingClassifAv1', StringType(), True),
                            StructField('financeiraCdtSerasaClassif', StringType(), True),
                            StructField('financeiraCdtSerasaClassifAv1', StringType(), True),
                            StructField('financeiraCdtSitCpfCnpjRec', StringType(), True),
                            StructField('financeiraCdtSitCpfCnpjRecAv1', StringType(), True),
                            StructField('financeiraCdtListaReal', StringType(), True),
                            StructField('financeiraCdtListaRealAv1', StringType(), True),
                            StructField('financeiraCdtQtDiasMaiorAtraso', StringType(), True),
                            StructField('financeiraCdtCdVarLivreThCli', StringType(), True),
                            StructField('financeiraCdtListaAymore', StringType(), True),
                            StructField('financeiraCdtListaAymoreAv1', StringType(), True),
                            StructField('financeiraCdtCdClassifCli', StringType(), True),
                            StructField('financeiraCdtCdClassficCliAv1', StringType(), True),
                            StructField('financeiraCdtCdGrauSeveridadeCli', StringType(), True),
                            StructField('financeiraCdtCdGrauSeveridadeAv1', StringType(), True),
                            StructField('financeiraCdtCl03Cli', StringType(), True),
                            StructField('financeiraCdtCl04Cli', StringType(), True),
                            StructField('financeiraCdtCl05Cli', StringType(), True),
                            StructField('financeiraCdtCl06Cli', StringType(), True),
                            StructField('financeiraCdtCl07Cli', StringType(), True),
                            StructField('financeiraCdtAb01Cli', StringType(), True),
                            StructField('financeiraCdtAb02Cli', StringType(), True),
                            StructField('financeiraCdtAb03Cli', StringType(), True),
                            StructField('financeiraCdtAb04Cli', StringType(), True),
                            StructField('financeiraCdtAb05Cli', StringType(), True),
                            StructField('financeiraCdtAb06Cli', StringType(), True),
                            StructField('financeiraCdtAb07Cli', StringType(), True),
                            StructField('financeiraCdtAb08Cli', StringType(), True),
                            StructField('financeiraCdtAb09Cli', StringType(), True),
                            StructField('financeiraCdtAb10Cli', StringType(), True),
                            StructField('financeiraCdtAb11Cli', StringType(), True),
                            StructField('financeiraCdtAb12Cli', StringType(), True),
                            StructField('financeiraCdtAb13Cli', StringType(), True),
                            StructField('financeiraCdtAb14Cli', StringType(), True),
                            StructField('financeiraCdtAb15Cli', StringType(), True),
                            StructField('financeiraCdtAe01Cli', StringType(), True),
                            StructField('financeiraCdtAe02Cli', StringType(), True),
                            StructField('financeiraCdtAe03Cli', StringType(), True),
                            StructField('financeiraCdtAe04Cli', StringType(), True),
                            StructField('financeiraCdtAe05Cli', StringType(), True),
                            StructField('financeiraCdtAe06Cli', StringType(), True),
                            StructField('financeiraCdtAe07Cli', StringType(), True),
                            StructField('financeiraCdtAe08Cli', StringType(), True),
                            StructField('financeiraCdtAe09Cli', StringType(), True),
                            StructField('financeiraCdtAe10Cli', StringType(), True),
                            StructField('financeiraCdtAo01Cli', StringType(), True),
                            StructField('financeiraCdtAo02Cli', StringType(), True),
                            StructField('financeiraCdtStConsultaCtpCli', StringType(), True),
                            StructField('financeiraCdtIcPossuiVeicCli', StringType(), True),
                            StructField('financeiraCdtVlGarMedVeicTotCli', StringType(), True),
                            StructField('financeiraCdtVlMedVeicQuiHstCli', StringType(), True),
                            StructField('financeiraCdtIdMediaVeicAdqCli', StringType(), True),
                            StructField('financeiraCdtTpUltAlienacaoCli', StringType(), True),
                            StructField('financeiraCdtQtTotVeicQuiCli', StringType(), True),
                            StructField('financeiraCdtQtVEicAtuFinCli', StringType(), True),
                            StructField('financeiraCdtQtVEicAtuaisCli', StringType(), True),
                            StructField('financeiraCdtQtVeicHistCli', StringType(), True),
                            StructField('financeiraCdtIcVeicFinCli', StringType(), True),
                            StructField('financeiraCdtIcVeic2FinCli', StringType(), True),
                            StructField('financeiraCdtIcVeicAtuHstCli', StringType(), True),
                            StructField('financeiraCdtIcVeic2AtuHstCli', StringType(), True),
                            StructField('financeiraCdtIcVeic3AtuHstCli', StringType(), True),
                            StructField('financeiraCdtIcFinAtivQuiCli', StringType(), True),
                            StructField('financeiraCdtIcFin2AtivQuiCli', StringType(), True),
                            StructField('financeiraCdtIcFin3AtivQuiCli', StringType(), True),
                            StructField('financeiraCdtQtPrazo1DecorrCli', StringType(), True),
                            StructField('financeiraCdtQtPrazo2DecorrCli', StringType(), True),
                            StructField('financeiraCdtQtPrazo3DecorrCli', StringType(), True),
                            StructField('flagFraudeHist', StringType(), True),
                            StructField('flagFunc', StringType(), True),
                            StructField('flagMonoprodutista', StringType(), True),
                            StructField('flagCorrentista', StringType(), True),
                            StructField('flagVinculoCc', StringType(), True),
                            StructField('flagPossuiCtrSim', StringType(), True),
                            StructField('flagRendaBalde', StringType(), True),
                            StructField('flagNivelConfianca', StringType(), True),
                            StructField('flagPAP', StringType(), True),
                            StructField('flagCupom', StringType(), True),
                            StructField('flagPublico', StringType(), True),
                            StructField('flagPreRatingSimPEM', StringType(), True),
                            StructField('flagPossuiAutoQuitado', StringType(), True),
                            StructField('flagPossuiMotoQuitado', StringType(), True),
                            StructField('flagCcVlrInvestimento', StringType(), True),
                            StructField('flagCcSegmentacaoPrimaria', StringType(), True),
                            StructField('flagCcSegmentacaoSecundaria', StringType(), True),
                            StructField('flagQtdDiasAtrasoContratoSim', StringType(), True),
                            StructField('flagNegadoUlt30DiasSim', StringType(), True),
                            StructField('flagSaldoInternoCartao', StringType(), True),
                            StructField('flagSaldoInternoCheque', StringType(), True),
                            StructField('flagSaldoInternoCp', StringType(), True),
                            StructField('flagSaldoInternoReneg', StringType(), True),
                            StructField('flagCadusQtdeRestrAtivCli', StringType(), True),
                            StructField('flagCadusVlrTotalRestrAtivCli', StringType(), True),
                            StructField('flagPEM01', StringType(), True),
                            StructField('flagPEM02', StringType(), True),
                            StructField('flagPEM03', StringType(), True),
                            StructField('flagPEM04', StringType(), True),
                            StructField('flagPEM05', StringType(), True),
                            StructField('flagPEM06', StringType(), True),
                            StructField('flagPEM07', StringType(), True),
                            StructField('flagPEM08', StringType(), True),
                            StructField('flagPEM09', StringType(), True),
                            StructField('flagPEM10', StringType(), True),
                            StructField('clearSaleID', StringType(), True),
                            StructField('clearSaleScoreDti', StringType(), True),
                            StructField('clearSaleDigital', StringType(), True),
                            StructField('serasaScoreSCDB', StringType(), True),
                            StructField('serasaScoreSCDJ ', StringType(), True),
                            StructField('serasaScoreCSDK', StringType(), True),
                            StructField('serasaNegativoSPC', StringType(), True),
                            StructField('serasaMosaic', StringType(), True),
                            StructField('serasaDuploScoreCSBZ', StringType(), True),
                            StructField('serasaCodigoProfissao', StringType(), True),
                            StructField('serasaAffordability', StringType(), True),
                            StructField('serasaRendaPro', StringType(), True),
                            StructField('serasaConfiabilidadeRegra', StringType(), True),
                            StructField('quodScore', StringType(), True),
                            StructField('quodSegmento', StringType(), True),
                            StructField('emailAgeScoreEA', StringType(), True),
                            StructField('emailAgeScoreClearSale', StringType(), True),
                            StructField('threatMetrixPolicyScore', StringType(), True),
                            StructField('threatMetrixReasonCode', StringType(), True),
                            StructField('threatMetrixRiskRating', StringType(), True),
                            StructField('threatMetrixReviewStatus', StringType(), True),
                            StructField('serasaCai5', StringType(), True),
                            StructField('serasaCai6', StringType(), True),
                            StructField('serasaCai7', StringType(), True),
                            StructField('serasaCai8', StringType(), True),
                            StructField('serasaCalgCai9', StringType(), True),
                            StructField('serasaAlertaNegocios', StringType(), True),
                            StructField('serasaLogradouro', StringType(), True),
                            StructField('allCheckLogradouro', StringType(), True),
                            StructField('telesineLogradouro ', StringType(), True)
                     ])),
                     StructField("logTrace",StructType([
                            StructField('nomeRegra', StringType(), True),
                            StructField('mensagem', StringType(), True)
                     ]))

])


connectionString = "Endpoint=sb://azredeevthub.servicebus.windows.net/;SharedAccessKeyName=Listner;SharedAccessKey=hhasroRvz/PwC/1Y479yqP1vJCnKEHoXCaknPTlPVT4=;EntityPath=fc_payload_analise_full_blaze_output"

ehConf = {
  'eventhubs.connectionString' : connectionString,
  'eventhubs.consumergroup' : "batch"
}

df = spark.readStream.format("eventhubs").options(**ehConf).load()

messages = df.withColumn(
                    "body",
                    df["body"].cast("string"))\
                        .select(from_json("body",schema).alias("body"))\
                        .select(
                                "body.cabecalho.cpf",
                                "body.cabecalho.telefone",
                                "body.cabecalho.timestamp",
                                "body.cabecalho.identificador-job",
                                "body.cabecalho.session-id",
                                "body.cabecalho.sistema-origem",
                                "body.cabecalho.tipo-transacao",
	                            "body.output-motor-analise-full.similaridadeFoneticaCadSerasa",
                                "body.output-motor-analise-full.similaridadeFoneticaCadAllCheck",
                                "body.output-motor-analise-full.similaridadeFoneticaCadTelesign",
                                "body.output-motor-analise-full.ratingFraudeFull",
                                "body.output-motor-analise-full.ratingDti",
                                "body.output-motor-analise-full.ratingQuod",
                                "body.output-motor-analise-full.ratingSim",
                                "body.output-motor-analise-full.ratingFinanceira",
                                "body.output-motor-analise-full.ratingFinal",
                                "body.output-motor-analise-full.statusDecisaoFull",
                                "body.output-motor-analise-full.cmasDirecionamentos",
                                "body.output-motor-analise-full.apontamentoGrupo1",
                                "body.output-motor-analise-full.apontamentoGrupo2",
                                "body.output-motor-analise-full.apontamentoGrupo3",
                                "body.output-motor-analise-full.apontamentoGrupo4",
                                "body.output-motor-analise-full.apontamentoGrupo5",
                                "body.output-motor-analise-full.apontamentoGrupo6",
                                "body.output-motor-analise-full.apontamentoGrupo7",
                                "body.output-motor-analise-full.apontamentoGrupo8",
                                "body.output-motor-analise-full.apontamentoGrupo9",
                                "body.output-motor-analise-full.apontamentoGrupo10",
                                "body.output-motor-analise-full.reasoncodeBlaze1",
                                "body.output-motor-analise-full.reasoncodeBlaze2",
                                "body.output-motor-analise-full.reasoncodeBlaze3",
                                "body.output-motor-analise-full.reasoncodeBlaze4",
                                "body.output-motor-analise-full.reasoncodeBlaze5",
                                "body.output-motor-analise-full.reasoncodeBlaze6",
                                "body.output-motor-analise-full.reasoncodeBlaze7",
                                "body.output-motor-analise-full.reasoncodeBlaze8",
                                "body.output-motor-analise-full.reasoncodeBlaze9",
                                "body.output-motor-analise-full.reasoncodeBlaze10",
                                "body.output-motor-analise-full.mensagemReasoncode1",
                                "body.output-motor-analise-full.mensagemReasoncode2",
                                "body.output-motor-analise-full.mensagemReasoncode3",
                                "body.output-motor-analise-full.mensagemReasoncode4",
                                "body.output-motor-analise-full.mensagemReasoncode5",
                                "body.output-motor-analise-full.mensagemReasoncode6",
                                "body.output-motor-analise-full.mensagemReasoncode7",
                                "body.output-motor-analise-full.mensagemReasoncode8",
                                "body.output-motor-analise-full.mensagemReasoncode9",
                                "body.output-motor-analise-full.mensagemReasoncode10",
                                "body.logInput.vivereIdProposta",
                                "body.logInput.vivereDataProposta",
                                "body.logInput.vivereCampanha",
                                "body.logInput.vivereDiaSemanaInclusao",
                                "body.logInput.vivereTimestampRequisicao",
                                "body.logInput.vivereCpfCliente",
                                "body.logInput.vivereDataNascimento",
                                "body.logInput.vivereDataUltimoResetSenha",
                                "body.logInput.vivereSessionId",
                                "body.logInput.vivereIP",
                                "body.logInput.vivereDescricaoDevice",
                                "body.logInput.vivereGeolocalizacaoDevice",
                                "body.logInput.financeiraCodigoProduto",
                                "body.logInput.financeiraTipoPessoa",
                                "body.logInput.dmpsQuantidadeDiasCarencia",
                                "body.logInput.financeiraCodigoObjeto",
                                "body.logInput.dmpsIdade",
                                "body.logInput.vivereVeiculoMarca",
                                "body.logInput.vivereVeiculoAnoModelo",
                                "body.logInput.vivereVeiculoAnoFabricacao",
                                "body.logInput.vivereVeiculoUfPlaca",
                                "body.logInput.vivereVeiculoUfLicenciamento",
                                "body.logInput.vivereVeiculoValorFIPE",
                                "body.logInput.vivereCedenteCnpj",
                                "body.logInput.vivereBoletoValorAPagar",
                                "body.logInput.vivereBoletoDataVencimento",
                                "body.logInput.vivereCedenteBanco",
                                "body.logInput.vivereFaturaValorAPagar",
                                "body.logInput.vivereFaturaDataVencimento",
                                "body.logInput.vivereBanco",
                                "body.logInput.vivereSubSegmento",
                                "body.logInput.vivereTAB",
                                "body.logInput.vivereValorSolicitado",
                                "body.logInput.vivereValorFinanciado",
                                "body.logInput.vivereParcela",
                                "body.logInput.viverePrazo",
                                "body.logInput.vivereTaxaNominalMensal",
                                "body.logInput.vivereTaxaNominalAnual",
                                "body.logInput.vivereTaxaCETMensal",
                                "body.logInput.vivereTaxaCETAnual",
                                "body.logInput.vivereFormaPagamento",
                                "body.logInput.vivereDataVencimentoSelecionada",
                                "body.logInput.vivereDataVencimentoPrimeiraParcela",
                                "body.logInput.vivereProponenteSexo",
                                "body.logInput.vivereProponenteNaturalidadeUF",
                                "body.logInput.vivereProponenteNaturalidadeCidade",
                                "body.logInput.vivereProponenteProfissao",
                                "body.logInput.vivereProponenteRenda",
                                "body.logInput.vivereProponenteCEP",
                                "body.logInput.vivereProponenteLogradouro",
                                "body.logInput.vivereProponenteEstado",
                                "body.logInput.vivereProponenteCidade",
                                "body.logInput.vivereAvalistaParentesco",
                                "body.logInput.vivereAvalistaCPF",
                                "body.logInput.vivereAvalistaDataNascimento",
                                "body.logInput.vivereAvalistaRenda",
                                "body.logInput.vivereAvalistaCEP",
                                "body.logInput.vivereAvalistaLogradouro",
                                "body.logInput.vivereAvalistaEstado",
                                "body.logInput.vivereAvalistaCidade",
                                "body.logInput.vivereOcupacao1",
                                "body.logInput.vivereRenda1",
                                "body.logInput.vivereOcupacao2",
                                "body.logInput.vivereRenda2",
                                "body.logInput.vivereOcupacao3",
                                "body.logInput.vivereRenda3",
                                "body.logInput.vivereOcupacao4",
                                "body.logInput.vivereRenda4",
                                "body.logInput.vivereOcupacao5",
                                "body.logInput.vivereRenda5",
                                "body.logInput.vivereNomeEmpresa",
                                "body.logInput.vivereDataAdmissao",
                                "body.logInput.vivereCNPJ",
                                "body.logInput.vivereFonteRendaCEP",
                                "body.logInput.vivereFonteRendaEstado",
                                "body.logInput.vivereFonteRendaCidade",
                                "body.logInput.financeiraRepesc",
                                "body.logInput.financeiraCdtQtdPefinRes6MCli",
                                "body.logInput.financeiraCdtQtdPefinRes12MCli",
                                "body.logInput.financeiraQtdOcoAtvSerasaCli",
                                "body.logInput.financeiraTmpOcoAtvNegMRecCli",
                                "body.logInput.financeiraTmpOcoResNegMRecCli",
                                "body.logInput.financeiraQtdOcoAcm1d12MCli",
                                "body.logInput.financeiraCdtQtdOcoAcm90d12MCli",
                                "body.logInput.financeiraVlrMaxOcoNeg12MCli",
                                "body.logInput.financeiraCdtTmpOcoNegRec12MCli",
                                "body.logInput.financeiraCdtVlrTotOcoNeg12MCli",
                                "body.logInput.financeiraCdtTmpMdRResSccf12MCli",
                                "body.logInput.financeiraCdtQtdCcfAtv12MCli",
                                "body.logInput.financeiraCdtQtdCcfRes12MCli",
                                "body.logInput.financeiraCdtQtdCcfAtvCli",
                                "body.logInput.financeiraCdtQtdAcoesRes12MCli",
                                "body.logInput.financeiraCdtQtdRefinAtvCli",
                                "body.logInput.financeiraCdtQtdRefinAtv12MCli",
                                "body.logInput.financeiraCdtQtdRefinRes6MCli",
                                "body.logInput.financeiraCdtQtdRefinRes12MCli",
                                "body.logInput.financeiraCdtQtdPefinAtvCli",
                                "body.logInput.financeiraQtdPefinAtv12MCli",
                                "body.logInput.financeiraQtdProAtvCli",
                                "body.logInput.financeiraQtdProRes12MCli",
                                "body.logInput.financeiraQtdRestAtvRes12MCli",
                                "body.logInput.financeiraQtdAcoesAtvCli",
                                "body.logInput.financeiraCdtIcConsultaCadusCli",
                                "body.logInput.financeiraCdtCdExperAbn",
                                "body.logInput.financeiraCdtCdExperAbnAv1",
                                "body.logInput.financeiraCdtQtUsoCpf",
                                "body.logInput.financeiraCdtCdCrb",
                                "body.logInput.financeiraCdtCdCrbAv1",
                                "body.logInput.financeiraCdtRatingClassif",
                                "body.logInput.financeiraCdtRatingClassifAv1",
                                "body.logInput.financeiraCdtSerasaClassif",
                                "body.logInput.financeiraCdtSerasaClassifAv1",
                                "body.logInput.financeiraCdtSitCpfCnpjRec",
                                "body.logInput.financeiraCdtSitCpfCnpjRecAv1",
                                "body.logInput.financeiraCdtListaReal",
                                "body.logInput.financeiraCdtListaRealAv1",
                                "body.logInput.financeiraCdtQtDiasMaiorAtraso",
                                "body.logInput.financeiraCdtCdVarLivreThCli",
                                "body.logInput.financeiraCdtListaAymore",
                                "body.logInput.financeiraCdtListaAymoreAv1",
                                "body.logInput.financeiraCdtCdClassifCli",
                                "body.logInput.financeiraCdtCdClassficCliAv1",
                                "body.logInput.financeiraCdtCdGrauSeveridadeCli",
                                "body.logInput.financeiraCdtCdGrauSeveridadeAv1",
                                "body.logInput.financeiraCdtCl03Cli",
                                "body.logInput.financeiraCdtCl04Cli",
                                "body.logInput.financeiraCdtCl05Cli",
                                "body.logInput.financeiraCdtCl06Cli",
                                "body.logInput.financeiraCdtCl07Cli",
                                "body.logInput.financeiraCdtAb01Cli",
                                "body.logInput.financeiraCdtAb02Cli",
                                "body.logInput.financeiraCdtAb03Cli",
                                "body.logInput.financeiraCdtAb04Cli",
                                "body.logInput.financeiraCdtAb05Cli",
                                "body.logInput.financeiraCdtAb06Cli",
                                "body.logInput.financeiraCdtAb07Cli",
                                "body.logInput.financeiraCdtAb08Cli",
                                "body.logInput.financeiraCdtAb09Cli",
                                "body.logInput.financeiraCdtAb10Cli",
                                "body.logInput.financeiraCdtAb11Cli",
                                "body.logInput.financeiraCdtAb12Cli",
                                "body.logInput.financeiraCdtAb13Cli",
                                "body.logInput.financeiraCdtAb14Cli",
                                "body.logInput.financeiraCdtAb15Cli",
                                "body.logInput.financeiraCdtAe01Cli",
                                "body.logInput.financeiraCdtAe02Cli",
                                "body.logInput.financeiraCdtAe03Cli",
                                "body.logInput.financeiraCdtAe04Cli",
                                "body.logInput.financeiraCdtAe05Cli",
                                "body.logInput.financeiraCdtAe06Cli",
                                "body.logInput.financeiraCdtAe07Cli",
                                "body.logInput.financeiraCdtAe08Cli",
                                "body.logInput.financeiraCdtAe09Cli",
                                "body.logInput.financeiraCdtAe10Cli",
                                "body.logInput.financeiraCdtAo01Cli",
                                "body.logInput.financeiraCdtAo02Cli",
                                "body.logInput.financeiraCdtStConsultaCtpCli",
                                "body.logInput.financeiraCdtIcPossuiVeicCli",
                                "body.logInput.financeiraCdtVlGarMedVeicTotCli",
                                "body.logInput.financeiraCdtVlMedVeicQuiHstCli",
                                "body.logInput.financeiraCdtIdMediaVeicAdqCli",
                                "body.logInput.financeiraCdtTpUltAlienacaoCli",
                                "body.logInput.financeiraCdtQtTotVeicQuiCli",
                                "body.logInput.financeiraCdtQtVEicAtuFinCli",
                                "body.logInput.financeiraCdtQtVEicAtuaisCli",
                                "body.logInput.financeiraCdtQtVeicHistCli",
                                "body.logInput.financeiraCdtIcVeicFinCli",
                                "body.logInput.financeiraCdtIcVeic2FinCli",
                                "body.logInput.financeiraCdtIcVeicAtuHstCli",
                                "body.logInput.financeiraCdtIcVeic2AtuHstCli",
                                "body.logInput.financeiraCdtIcVeic3AtuHstCli",
                                "body.logInput.financeiraCdtIcFinAtivQuiCli",
                                "body.logInput.financeiraCdtIcFin2AtivQuiCli",
                                "body.logInput.financeiraCdtIcFin3AtivQuiCli",
                                "body.logInput.financeiraCdtQtPrazo1DecorrCli",
                                "body.logInput.financeiraCdtQtPrazo2DecorrCli",
                                "body.logInput.financeiraCdtQtPrazo3DecorrCli",
                                "body.logInput.flagFraudeHist",
                                "body.logInput.flagFunc",
                                "body.logInput.flagMonoprodutista",
                                "body.logInput.flagCorrentista",
                                "body.logInput.flagVinculoCc",
                                "body.logInput.flagPossuiCtrSim",
                                "body.logInput.flagRendaBalde",
                                "body.logInput.flagNivelConfianca",
                                "body.logInput.flagPAP",
                                "body.logInput.flagCupom",
                                "body.logInput.flagPublico",
                                "body.logInput.flagPreRatingSimPEM",
                                "body.logInput.flagPossuiAutoQuitado",
                                "body.logInput.flagPossuiMotoQuitado",
                                "body.logInput.flagCcVlrInvestimento",
                                "body.logInput.flagCcSegmentacaoPrimaria",
                                "body.logInput.flagCcSegmentacaoSecundaria",
                                "body.logInput.flagQtdDiasAtrasoContratoSim",
                                "body.logInput.flagNegadoUlt30DiasSim",
                                "body.logInput.flagSaldoInternoCartao",
                                "body.logInput.flagSaldoInternoCheque",
                                "body.logInput.flagSaldoInternoCp",
                                "body.logInput.flagSaldoInternoReneg",
                                "body.logInput.flagCadusQtdeRestrAtivCli",
                                "body.logInput.flagCadusVlrTotalRestrAtivCli",
                                "body.logInput.flagPEM01",
                                "body.logInput.flagPEM02",
                                "body.logInput.flagPEM03",
                                "body.logInput.flagPEM04",
                                "body.logInput.flagPEM05",
                                "body.logInput.flagPEM06",
                                "body.logInput.flagPEM07",
                                "body.logInput.flagPEM08",
                                "body.logInput.flagPEM09",
                                "body.logInput.flagPEM10",
                                "body.logInput.clearSaleID",
                                "body.logInput.clearSaleScoreDti",
                                "body.logInput.clearSaleDigital",
                                "body.logInput.serasaScoreSCDB",
                                "body.logInput.serasaScoreSCDJ",
                                "body.logInput.serasaScoreCSDK",
                                "body.logInput.serasaNegativoSPC",
                                "body.logInput.serasaMosaic",
                                "body.logInput.serasaDuploScoreCSBZ",
                                "body.logInput.serasaCodigoProfissao",
                                "body.logInput.serasaAffordability",
                                "body.logInput.serasaRendaPro",
                                "body.logInput.serasaConfiabilidadeRegra",
                                "body.logInput.quodScore",
                                "body.logInput.quodSegmento",
                                "body.logInput.emailAgeScoreEA",
                                "body.logInput.emailAgeScoreClearSale",
                                "body.logInput.threatMetrixPolicyScore",
                                "body.logInput.threatMetrixReasonCode",
                                "body.logInput.threatMetrixRiskRating",
                                "body.logInput.threatMetrixReviewStatus",
                                "body.logInput.serasaCai5",
                                "body.logInput.serasaCai6",
                                "body.logInput.serasaCai7",
                                "body.logInput.serasaCai8",
                                "body.logInput.serasaCalgCai9",
                                "body.logInput.serasaAlertaNegocios",
                                "body.logInput.serasaLogradouro",
                                "body.logInput.allCheckLogradouro",
                                "body.logInput.telesineLogradouro",
                                "body.logTrace.nomeRegra",
                                "body.logTrace.mensagem"
                                )

messages.writeStream.outputMode("append")\
                    .format("csv")\
                    .option("sep", ";") \
                    .option("path","/data/raw/FICO/PayloadAnaliseFullBlazeOutput/streaming")\
                    .option("checkpointLocation","/data/raw/FICO/payloadanalisefullblazeoutput/streaming/checkpoint")\
                    .start().awaitTermination()


